#!/usr/bin/env python3
"""
c98_release.py -- assemble `release/`, the deposit-ready artefact for the DOI.

    python3 analysis/c98_release.py            # build into <repo>/release
    python3 analysis/c98_release.py --outdir X # elsewhere

The build is deterministic and idempotent: it copies from the working tree,
regenerates the four figures, runs the reproduction audit, writes README.md,
ENVIRONMENT.md, Makefile, CITATION.cff and MANIFEST.md5, and refuses to finish if
the audit reports a failed check.  The README's headline numbers are GENERATED by
the audit, not typed, so the artefact cannot ship a number the CSV disagrees with.
"""
import argparse, hashlib, io, os, shutil, subprocess, sys, tarfile, textwrap, time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
BACKUP = os.path.normpath(os.path.join(ROOT, ".."))
sys.path.insert(0, HERE)

SCORERS = ["c76_mm1_score.py", "c77_pp1_score.py", "c78_bn1_score.py",
           "c81_cc1_score.py", "c82_fa1_score.py", "c83_gc1_score.py",
           "c83_gen_score.py", "c84_gn1_score.py", "c87_rl3_score.py",
           "c87_hz3_score.py", "c88_scorers.py", "c97_bm2_score.py",
           "c97_rp1_score.py", "c97_sm4_score.py"]
TOOLS   = ["aggregate.py", "args_repair.py", "argsline_guard.py",
           "c98_figures.py", "c98_reproduce.py", "c98_release.py"]
DOCS    = ["CORRECTIONS.md", "ARGS-AUDIT.md", "DATASETS.md", "OPERATIONS.md",
           "MASTER-TABLE.md"]

def sh(cmd, cwd=ROOT):
    try:
        return subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True,
                              text=True, timeout=600)
    except Exception as e:
        class R: returncode, stdout, stderr = 1, "", str(e)
        return R()

def md5(path, chunk=1 << 20):
    h = hashlib.md5()
    with open(path, "rb") as fh:
        for b in iter(lambda: fh.read(chunk), b""): h.update(b)
    return h.hexdigest()

def copy(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=os.path.join(ROOT, "release"))
    ap.add_argument("--skip-logs", action="store_true",
                    help="do not build logs/raw_out.tar.gz (much faster)")
    a = ap.parse_args()
    OUT = os.path.abspath(a.outdir)
    if os.path.isdir(OUT): shutil.rmtree(OUT)
    os.makedirs(OUT)

    commit = (sh("git rev-parse HEAD").stdout or "").strip() or "unknown"
    short  = commit[:7]
    dirty  = bool((sh("git status --porcelain").stdout or "").strip())

    # ---- 1. regenerate the figures, then run the audit -----------------------
    print("[1/6] regenerating figures")
    r = sh("%s analysis/c98_figures.py --all" % sys.executable)
    if r.returncode: sys.exit("figure build failed:\n" + r.stderr)
    print("[2/6] running the reproduction audit")
    r = sh("%s analysis/c98_reproduce.py" % sys.executable)
    audit = r.stdout
    if r.returncode:
        sys.exit("REFUSING TO BUILD: the reproduction audit failed.\n" + audit)

    # ---- 2. copy the payload -------------------------------------------------
    print("[3/6] copying data, code, scripts, patches, figures, docs")
    copy(os.path.join(ROOT, "results", "all_runs.csv"),
         os.path.join(OUT, "data", "all_runs.csv"))
    for f in SCORERS:
        p = os.path.join(ROOT, "analysis", f)
        if os.path.exists(p): copy(p, os.path.join(OUT, "code", "scorers", f))
    for f in TOOLS:
        p = os.path.join(ROOT, "analysis", f)
        if os.path.exists(p): copy(p, os.path.join(OUT, "code", f))
    for d, sub in (("bin", "scripts"), ("patches", "code/patches"),
                   ("tests", "code/tests")):
        src = os.path.join(ROOT, d)
        for f in sorted(os.listdir(src)):
            p = os.path.join(src, f)
            if os.path.isfile(p) and not f.endswith(".pyc"):
                copy(p, os.path.join(OUT, sub.replace("/", os.sep), f))
    for f in sorted(os.listdir(os.path.join(ROOT, "paper", "figures"))):
        copy(os.path.join(ROOT, "paper", "figures", f),
             os.path.join(OUT, "figures", f))
    for f in DOCS:
        p = os.path.join(ROOT, "docs", f)
        if os.path.exists(p): copy(p, os.path.join(OUT, "docs", f))

    # ---- 3. the raw per-epoch logs, as one archive ---------------------------
    n_out, log_bytes = 0, 0
    if not a.skip_logs:
        print("[4/6] archiving the raw per-epoch .out logs")
        tgz = os.path.join(OUT, "logs", "raw_out.tar.gz")
        os.makedirs(os.path.dirname(tgz), exist_ok=True)
        with tarfile.open(tgz, "w:gz") as tf:
            for d in ("runs", "runs_alice2"):
                base = os.path.join(BACKUP, d)
                if not os.path.isdir(base): continue
                for dirpath, _, files in os.walk(base):
                    for f in sorted(files):
                        if not f.endswith(".out"): continue
                        p = os.path.join(dirpath, f)
                        tf.add(p, arcname=os.path.join(d, os.path.relpath(p, base)))
                        n_out += 1; log_bytes += os.path.getsize(p)
    else:
        print("[4/6] SKIPPED raw log archive (--skip-logs)")

    # ---- 4. the generated text files ----------------------------------------
    print("[5/6] writing README, ENVIRONMENT, Makefile, CITATION")
    stamp = time.strftime("%Y-%m-%d", time.gmtime())
    open(os.path.join(OUT, "REPRODUCTION-AUDIT.txt"), "w").write(audit)

    open(os.path.join(OUT, "Makefile"), "w").write(MAKEFILE)
    open(os.path.join(OUT, "code", "verify_manifest.py"), "w").write(VERIFIER)
    open(os.path.join(OUT, "ENVIRONMENT.md"), "w").write(ENVIRONMENT)
    open(os.path.join(OUT, "CITATION.cff"), "w").write(CITATION % dict(date=stamp))
    open(os.path.join(OUT, "README.md"), "w").write(README % dict(
        stamp=stamp, commit=commit, short=short,
        dirty=("  **The working tree was DIRTY at build time; re-build from a "
               "clean checkout before minting the DOI.**" if dirty else ""),
        n_out=n_out, log_mb=log_bytes / 1e6,
        audit_head="\n".join("    " + x for x in audit.splitlines()[:8]).lstrip(),
    ))

    # ---- 5. the manifest -----------------------------------------------------
    print("[6/6] writing MANIFEST.md5")
    lines, total, nfiles = [], 0, 0
    for dirpath, dirs, files in os.walk(OUT):
        dirs.sort()
        for f in sorted(files):
            if f == "MANIFEST.md5": continue
            p = os.path.join(dirpath, f)
            rel = os.path.relpath(p, OUT)
            lines.append("%s  %10d  %s" % (md5(p), os.path.getsize(p), rel))
            total += os.path.getsize(p); nfiles += 1
    with open(os.path.join(OUT, "MANIFEST.md5"), "w") as fh:
        fh.write("# md5  bytes  path      -- %d files, %.1f MB, built %s from %s\n"
                 % (nfiles, total / 1e6, stamp, short))
        fh.write("\n".join(lines) + "\n")
    print("\nrelease/ built: %d files, %.1f MB" % (nfiles, total / 1e6))
    print("verify with:  cd %s && make verify" % os.path.relpath(OUT, os.getcwd()))

# ------------------------------------------------------------------ templates
VERIFIER = '''#!/usr/bin/env python3
"""Check every file in this artefact against MANIFEST.md5.  Exit 0 iff all match."""
import hashlib, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
bad = n = 0
for line in open(os.path.join(ROOT, "MANIFEST.md5")):
    if line.startswith("#") or not line.strip():
        continue
    h, _size, rel = line.split(None, 2)
    rel = rel.rstrip("\\n")
    p = os.path.join(ROOT, rel)
    n += 1
    if not os.path.exists(p):
        print("MISSING  %s" % rel); bad += 1; continue
    d = hashlib.md5(open(p, "rb").read()).hexdigest()
    if d != h:
        print("CHANGED  %s" % rel); bad += 1
print("%d files checked, %d bad" % (n, bad))
sys.exit(1 if bad else 0)
'''

MAKEFILE = r"""# Reproduce the paper's numbers and figures from this artefact.
#
#   make reproduce        every headline number, re-derived and checked
#   make reproduce-table2 just Table 2 / Figure 1
#   make figures          rebuild the four figures into figures/
#   make logs             unpack the raw per-epoch logs (needed by `make figures`
#                         for Figure 3, which is paired WITHIN run)
#   make verify           check every file against MANIFEST.md5
#   make all              logs, reproduce, figures
#
# Requires: python3 >= 3.8, matplotlib. Nothing else. No GPU. Runs in seconds.

PY ?= python3

.PHONY: all reproduce reproduce-table2 figures logs verify clean

all: logs reproduce figures

reproduce:
	$(PY) code/c98_reproduce.py --csv data/all_runs.csv

reproduce-table2:
	$(PY) code/c98_reproduce.py --csv data/all_runs.csv --table2 --heterogeneity

figures:
	$(PY) code/c98_figures.py --all --numbers --csv data/all_runs.csv --outdir figures

logs:
	@test -d logs/runs || (cd logs && tar xzf raw_out.tar.gz && echo "unpacked")

verify:
	$(PY) code/verify_manifest.py

clean:
	rm -rf logs/runs logs/runs_alice2
"""

ENVIRONMENT = """# Environment

Every run in `data/all_runs.csv` was produced inside one virtual environment, on
one Slurm cluster, under two accounts. The two accounts' environments were
compared at write time and are byte-identical in every package that matters.

| | |
|---|---|
| Python | 3.10.4 (`Python/3.10.4-GCCcore-11.3.0` module) |
| PyTorch | **2.0.1+cu118** |
| CUDA (torch build) | **11.8** |
| torchvision | 0.15.2+cu118 |
| numpy | 1.26.4 |
| scheduler | Slurm |
| GPUs | NVIDIA L4 24 GB, RTX 2080 Ti 11 GB, A100 80 GB, A100 MIG 40 GB |
| distinct compute nodes | 29 |
| accounts | 2 (`salehkaleybars`, `s5014158`) |

GPU class is recorded per run in the `node` column and was measured to carry no
systematic offset between arms; every primary contrast is taken within one batch,
so a per-node offset shared by the two arms cancels identically.

**The analysis side needs none of this.** Reproducing every number in the paper
needs `python3` and `matplotlib` only — no GPU, no PyTorch, no cluster. The
optimiser environment above is what would be needed to *re-run* the experiments.

## Re-running an experiment

    module load Python/3.10.4-GCCcore-11.3.0
    . <workspace>/envs/mo/bin/activate
    # then submit any script in scripts/, e.g.
    sbatch scripts/c90_awbase.sh

Each script in `scripts/` carries numbered pre-submission guards: the run table
must be present, the required patches must be present in the live tree, the group
counts are **measured** on the instantiated optimiser and asserted equal to the
registered values, there must be no name collision with an existing batch, the
comparator batch must exist, and there must be disk and queue headroom.
"""

CITATION = """cff-version: 1.2.0
message: "If you use this artefact, please cite it."
title: "The partition, not the count: artefact"
abstract: >-
  Run table, raw per-epoch logs, submission scripts, optimiser patches, registered
  scorers and figure code for a count-matched measurement of step-size granularity
  in online meta-gradient optimisation.
type: dataset
license: CC-BY-4.0
date-released: "%(date)s"
identifiers:
  - type: doi
    value: "PENDING"
    description: >-
      Not yet minted. The deposit is prepared; the DOI is reserved at submission
      and inserted here and in the paper's Data-availability statement before
      camera-ready.
"""

README = """# Artefact: *The partition, not the count*

**DOI: PENDING.** The deposit is assembled and self-verifying; no DOI has been
minted yet. A Zenodo reserved DOI is taken at submission time and written into
this file, into `CITATION.cff`, and into the paper's Data-availability statement
before camera-ready. Until then, cite this artefact by repository commit
`%(short)s`.

Built %(stamp)s from commit `%(commit)s`.%(dirty)s

---

## What this is

Everything behind every number in the paper, and a script that re-derives them
and checks them against what the paper prints.

    make reproduce

runs in a few seconds on a laptop, needs `python3` and `matplotlib` and nothing
else, and exits non-zero if any headline number fails to reproduce. It prints one
line per number: *derived value | paper value | PASS/FAIL | where it appears*.

    %(audit_head)s

## Layout

| path | what |
|---|---|
| `data/all_runs.csv` | the run table of record. One row per run: full configuration (network, dataset, batch size, granularity, base, meta, η, α₀, γ, augmentation, β-box, hierarchical mode, λ, r, seed), outcomes (`best_test`, `final_test`, `plateau5`, `plateau`, `auc`, epochs-to-threshold), provenance (`job_id`, `account`, `node`, `wallclock_min`), and the two admissibility flags (`window_ok`, `complete`) |
| `logs/raw_out.tar.gz` | %(n_out)d raw Slurm `.out` files, %(log_mb).1f MB uncompressed — the per-epoch train/test series, plus each run's own `ARGS:` and `ENV:` line. `make logs` unpacks them |
| `code/c98_reproduce.py` | the audit. Re-derives every headline and checks it |
| `code/c98_figures.py` | the four figures, from the CSV, on one palette |
| `code/aggregate.py` | builds `all_runs.csv` from the raw `.out` files |
| `code/argsline_guard.py` | sweeps every run's own `ARGS:` line for a repeated flag |
| `code/args_repair.py` | writes the `dup_group` column for the 18 collapsed pairs |
| `code/scorers/` | the registered scorers. Each was committed **before** its batch's runs existed; each is run unedited and its printed verdict quoted |
| `code/patches/` | the optimiser patches against the released MetaOptimize `HF.py`, each with an identity test against the authors' own `blockwise` path |
| `code/tests/` | those identity tests |
| `scripts/` | every batch submission script, with its numbered pre-submission guards |
| `figures/` | the four figures, as PDF and PNG |
| `docs/` | the correction register (`CORRECTIONS.md`), the ARGS audit, the dataset provenance note |
| `REPRODUCTION-AUDIT.txt` | the audit output captured at build time |
| `MANIFEST.md5` | md5 and size of every file. `make verify` checks them |

## The rules the code enforces, so that a number cannot drift

* **`plateau5`** — the mean test accuracy over the last 5 epochs of the requested
  budget — is the only accuracy metric read. The CSV also carries `plateau`, the
  20-epoch analogue; it is **banned** as a primary and the code never reads it.
  Two headlines were withdrawn from an earlier draft for quoting it.
* **Admissibility** is `window_ok == 1 AND complete == 1 AND a readable plateau5`,
  applied before any arm mean is formed.
* **Every contrast is within one batch** — one contiguous submission — so any
  offset shared by the two arms cancels identically.
* **Rows sharing a `dup_group` are averaged within the group first**, and n counts
  distinct groups. This is what makes the `ml2` cell 3 v 3 (se 0.195) rather than
  6 v 6 (se 0.142): its two halves resolve to the same command line including the
  seed. See `docs/ARGS-AUDIT.md`.
* **CIFAR-10 and CIFAR-100 effects are never averaged or plotted on one
  percentage-point axis.** They sit on ≈7–8 pp and ≈29–30 pp error budgets.
  Figure 1 carries the rule as a hard axis break and gives the commensurable
  quantity, D / headroom, beside it.

## What is *not* here

* **The per-group β probe traces** (`probe*.jsonl`, ≈42 GB). They are what the
  box-occupancy checks read. They are excluded from this deposit for size and are
  available from the authors on request; the occupancy summaries they produce are
  in the run table (`beta_clip`) and in the scorers' output.
* **The CIFAR-10 / CIFAR-100 datasets**, which are standard public downloads and
  are fetched by `torchvision` at run time.

## License

Code and scripts: MIT. Data (`data/`, `logs/`, `docs/`): CC-BY-4.0. The optimiser
patches in `code/patches/` apply to the authors' released MetaOptimize
implementation and carry that work's own license; they are distributed here as
patches, not as a fork.
"""

if __name__ == "__main__":
    main()
